"""Add roles

Revision ID: b70483ea6be0
Revises: 
Create Date: 2026-04-20 16:35:58.037254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = 'b70483ea6be0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Get the database connection and inspector to check for existing objects
    connection = op.get_bind()
    inspector = inspect(connection)
    
    # Get list of existing tables, columns, and indexes
    existing_tables = inspector.get_table_names()
    existing_indexes = inspector.get_indexes('roles') if 'roles' in existing_tables else []
    users_columns = [col['name'] for col in inspector.get_columns('users')] if 'users' in existing_tables else []
    
    # Create roles table only if it doesn't exist
    if 'roles' not in existing_tables:
        op.create_table('roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    
    # Create index on id only if it doesn't exist
    if 'roles' in existing_tables:
        existing_index_names = [idx['name'] for idx in existing_indexes]
        if 'ix_roles_id' not in existing_index_names:
            op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
        
        # Create index on name only if it doesn't exist
        if 'ix_roles_name' not in existing_index_names:
            op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    
    # Add role_id column to users table only if it doesn't exist
    if 'users' in existing_tables and 'role_id' not in users_columns:
        op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    
    # Create foreign key only if role_id column was just added or exists but FK doesn't
    if 'users' in existing_tables and 'role_id' in users_columns:
        users_fks = inspector.get_foreign_keys('users')
        fk_exists = any(fk['constrained_columns'] == ['role_id'] and fk['referred_table'] == 'roles' for fk in users_fks)
        if not fk_exists:
            op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
