"""Add email_otp_tokens table

Revision ID: c8f5a1b2c3d4
Revises: b70483ea6be0
Create Date: 2026-05-11 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8f5a1b2c3d4'
down_revision: Union[str, None] = 'b70483ea6be0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_otp_tokens',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(255), nullable=False),
    sa.Column('otp_code', sa.String(255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=False), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('attempt_count', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('created_at', sa.DateTime(timezone=False), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.Column('ip_address', sa.String(45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_otp_tokens_id'), 'email_otp_tokens', ['id'], unique=False)
    op.create_index('ix_email_otp_tokens_email_is_used_expires', 'email_otp_tokens', ['email', 'is_used', 'expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_otp_tokens_email_is_used_expires', table_name='email_otp_tokens')
    op.drop_index(op.f('ix_email_otp_tokens_id'), table_name='email_otp_tokens')
    op.drop_table('email_otp_tokens')
    # ### end Alembic commands ###
